apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: B2B
  region: ap-southeast-2

vpc:
  id: "vpc-0625296b14616a368"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-southeast-2a: { id: 	subnet-0b532be25057083a5 }
      ap-southeast-2b: { id: 	subnet-05826c870daa8606a }
      ap-southeast-2c: { id:  subnet-0fa49bd1dfa5be4a4 }

managedNodeGroups:
  - name: node1
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    ssh: 
      allow: true
      publicKeyName: new
    tags:
      Name: node1
  - name: spot1
    instanceType: t3.small
    labels: { role: builders }
    minSize: 1
    maxSize: 2
    spot: true
    ssh: 
      allow: true
      publicKeyName: new
    tags:
      Name: spot1
